openapi: '3.0.2'

info:
  title: Content Trust in OCI Distribution
  description: Metadata API for signature related operations in an [OCI registry](https://github.com/opencontainers/distribution-spec).
  version: '1.0'

servers:
  - url: http://localhost:5000/v2

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    signatures:
      type: object
      description: The paginated list of signatures available for a given artifact.
      properties:
        digest:
          type: string
          description: The digest of the artifact manifest to which the signatures apply.
          example: sha256:90659bf80b44ce6be8234e6ff90a1ac34acbeb826903b02cfa0da11c82cbc042
        signatures:
          type: array
          items:
            type: string
            description: The digest of the signature manifest.
            example: sha256:2235d2d22ae5ef400769fa51c84717264cd1520ac8d93dc071374c1be49cc77c

    signature_config:
      $ref: "../signature/schema.json"

    manifest:
      $ref: "https://raw.githubusercontent.com/opencontainers/image-spec/master/schema/image-manifest-schema.json"

  parameters:
    repoParam:
      name: repository
      in: path
      description: The name of the repository.
      required: true
      schema:
        type: string

    digestParam:
      name: digest
      in: path
      description: The cryptographic checksum digest of the object, in the pattern '<algorithm>:<encoded>'
      required: true
      schema:
        type: string

    signatureManifestDigestParam:
      $ref: "#/components/parameters/digestParam"

paths:
  /{repository}/manifests/{digest}/signatures/:
    get:
      summary: Get paginated list of signatures that reference the given manifest digest in the given repository.
      operationId: getSignatures
      security:
        - basicAuth: []
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/repoParam"
        - $ref: "#/components/parameters/digestParam"
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/signatures"

  /{repository}/manifests/{digest}/signature/{digest}:
    put:
      summary: Link a signature to an image.
      operationId: putSignature
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/repoParam"
        - $ref: "#/components/parameters/digestParam"
        - $ref: "#/components/parameters/signatureManifestDigestParam"
      responses:
        '201':
          description: Accepted
